name: Block ZIP Downloads

on:
  push:
    branches:
      - main

jobs:
  delete_zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Delete ZIP files
        run: |
          rm -rf *.zip *.tar.gz
