name: Block ZIP Downloads
on:
  push:
    branches:
      - main

jobs:
  delete_zip:
    runs-on: ubuntu-latest
    steps:
      - name: Delete ZIP files
        run: |
          rm -rf *.zip *.tar.gz
